# Generated by Django 5.1 on 2024-08-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_on_sale_product_rating_product_sale_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_discount',
        ),
    ]
