# Generated by Django 5.1 on 2024-09-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_created_at_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='DEFAULT_ORDER_NUMBER', editable=False, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
